name: Beautiful Jekyll CI
on: [push, pull_request]
jobs:
  build:
    name: Build Jekyll
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
      - name: Install dependencies
        run: bundle install && bundle exec appraisal install
      - name: Setup Pages
        id: configure-pages
        uses: actions/configure-pages@v5
      - name: Setup CI config
        run: |
          echo "---" > _config_ci.yml
          echo "baseurl: ${{ steps.configure-pages.outputs.base_path }}" >> _config_ci.yml
      - name: Build site
        env:
          JEKYLL_ENV: production
        run: bundle exec appraisal jekyll build --future --config _config_ci.yml,_config.yml
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
      - name: Checkout submodules
        run: git submodule update --init --recursive

# name: Build and Deploy Jekyll Site

# on:
#   push:
#     branches:
#       - main  # Trigger on pushes to the main branch
#   pull_request:

# jobs:
#   build:
#     runs-on: ubuntu-latest
    
#     steps:
#       - name: Checkout Repository
#         uses: actions/checkout@v2
#         with:
#           submodules: recursive  # Ensures submodules are fetched and initialized

#       - name: Setup Ruby
#         uses: ruby/setup-ruby@v1
#         with:
#           ruby-version: 2.7  # Specify the Ruby version compatible with GitHub Pages

#       - name: Install Dependencies
#         run: |
#           gem install bundler
#           bundle install

#       - name: Build Jekyll Site
#         run: bundle exec jekyll build

#       - name: Deploy to GitHub Pages
#         uses: peaceiris/actions-gh-pages@v3
#         with:
#           github_token: ${{ secrets.GITHUB_TOKEN }}
#           publish_dir: ./_site  # Directory where Jekyll outputs the built site
